### PR TITLE
Fixed selected item's text not updating

### PR DESCRIPTION
**Pull request by dchavezlive**
When selecting an index the selected text wouldn't update: Fixes issue https://github.com/aryaxt/ScrollPager/issues/1

### CODE REVIEW

**Comment by aryaxt** [comment]
How do you reproduce the issue?  
I have the following code in viewDidLoad and everything works fine

```
scrollPager.setSelectedIndex(2, animated: true, moveScrollView: true)
```

**Comment by dchavezlive** [comment]
You may not be setting ```Selected Text Indicator Color``` the error is that when you select a new index, the indicator will change but the text won't change to reflect the newly selected index.

**Comment by mateusznadolski** [comment]
I'm also experiencing this issue. Although I was able to reproduce it only on devices that doesn't support 64-bit architecture.

Steps to reproduce:
- Run demo app in Simulator (choose e.g. iPhone 5)
- Change selected tab
- Selected text color is not updated

**Comment by dchavezlive** [comment]
It should be on all devices, as the ``moveToIndex(index:animated:moveScrollView:)``` code doesn't update the buttons.

**Comment by mateusznadolski** [comment]
@aryaxt have you  been able to reproduce this issue?

**Comment by aryaxt** [comment]
will look into it this weekend, but rather not do a copy pasta on the for loop, I'm guessing just calling setNeedsLayout would be enough.

**Comment by aryaxt** [comment]
@dchavezlive Sorry I ended up fixing this another way. closing this

**Pull request closed without merging**
